name: Deploy to Vercel

on:
  push:
    branches:
      - master  # 或者你的默认分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 这里可以指定你使用的 Node.js 版本

      - name: Install dependencies (client)
        run: |
          cd client/dataAnalize  # 前端目录
          npm install

      - name: Build the project (client)
        run: |
          cd client/dataAnalize  # 前端目录
          npm run build

      - name: Deploy to Vercel
        run: |
          # 在这里添加部署到 Vercel 的命令，具体视你的需求而定
          vercel --prod  # 这是 Vercel CLI 的命令
